---
# default
default: -p capybara -p webkit

# drivers
capybara: DRIVER=capybara --exclude features/fixtures/selenium --exclude features/fixtures/watir
selenium: DRIVER=selenium --exclude features/fixtures/capybara --exclude features/fixtures/watir
watir: DRIVER=watir --exclude features/fixtures/capybara --exclude features/fixtures/selenium

# browser
webkit: BROWSER=webkit
poltergeist: BROWSER=poltergeist
firefox: BROWSER=firefox
chrome: BROWSER=chrome
safari: BROWSER=safari
phantomjs: BROWSER=phantomjs
